CREATE DATABASE CLINICA;
DROP DATABASE CLINICA;
USE CLINICA;

CREATE TABLE MEDICO(
		MEDICO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
		MEDICO_NOME VARCHAR(255) NOT NULL);

DESCRIBE MEDICO;

INSERT INTO MEDICO(MEDICO_NOME) 
VALUES  ("HENRIQUE"),
	("NÁDIA"),
	("DIEGO");

SELECT * FROM MEDICO;

CREATE TABLE PACIENTE(
		PACIENTE_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
		PACIENTE_NOME VARCHAR(255) NOT NULL);
		
INSERT INTO PACIENTE(PACIENTE_NOME)
VALUES  ("JOÃO"),
	("RENAN"),
	("LARA");
	
SELECT * FROM PACIENTE;		

CREATE TABLE CONSULTA(
		CONSULTA_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
		FK_MEDICO INT(10) NOT NULL,
		FK_PACIENTE INT(10) NOT NULL,
		CONSTRAINT FK_MEDICO_ID FOREIGN KEY (FK_MEDICO) REFERENCES MEDICO(MEDICO_ID),
		CONSTRAINT FK_PACIENTE_ID FOREIGN KEY (FK_PACIENTE) REFERENCES PACIENTE(PACIENTE_ID));
		
INSERT INTO CONSULTA(FK_MEDICO, FK_PACIENTE) 
VALUES  (1,1),
	(2,2),
	(3,3);		
		
CREATE TABLE MEDICAMENTO(
		MEDICAMENTO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
		MEDICAMENTO_NOME VARCHAR(255) NOT NULL UNIQUE);
		
		
INSERT INTO MEDICAMENTO(MEDICAMENTO_NOME)
VALUES  ("RIVOTRIL"),
	("PARACETAMOL"),
	("DIPIRONA");
	
SELECT * FROM MEDICAMENTO;

CREATE TABLE PRESCRICAO(
	FK_CONSULTA INT(10) NOT NULL,
	FK_MEDICAMENTO INT(10) NOT NULL);
	
ALTER TABLE PRESCRICAO ADD CONSTRAINT FK_CONSULTA_ID FOREIGN KEY (FK_CONSULTA) REFERENCES CONSULTA(CONSULTA_ID) ON DELETE CASCADE;
ALTER TABLE PRESCRICAO ADD CONSTRAINT FK_MEDICAMENTO_ID FOREIGN KEY (FK_MEDICAMENTO) REFERENCES MEDICAMENTO(MEDICAMENTO_ID) ON DELETE CASCADE;

INSERT INTO PRESCRICAO(FK_CONSULTA, FK_MEDICAMENTO)
VALUES  (1,1),
	(2,2),
	(3,2);
SELECT * FROM PRESCRICAO WHERE FK_CONSULTA = 1;