CREATE DATABASE NETFLIX;
USE NETFLIX;

CREATE TABLE USUARIO(
	USUARIO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	USUARIO_USERNAME VARCHAR(255) NOT NULL UNIQUE,
	USUARIO_PASSWORD VARCHAR(255) NOT NULL,
	USUARIO_EMAIL VARCHAR(255) NOT NULL);
	
INSERT INTO USUARIO(USUARIO_USERNAME, USUARIO_PASSWORD,USUARIO_EMAIL)
VALUES  ("HENRIQUE","12345","HENRIQUE@LEMAIL.COM"),
	("ANA CAROLINA","45678","CAROLINA.ANA@LEMAIL.COM"),
	("RENATO","58172","RENATÃO@LEMAIL.COM");
	
SELECT * FROM USUARIO;

CREATE TABLE VIDEO(
	VIDEO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	VIDEO_TITULO VARCHAR(255) NOT NULL,
	VIDEO_CATEGORIA VARCHAR(255) NOT NULL,
	VIDEO_DATA DATE NOT NULL,
	VIDEO_HORA TIME NOT NULL,
	FK_USUARIO INT(10) NOT NULL,
	CONSTRAINT FK_USUARIO_ID FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(USUARIO_ID));

INSERT INTO VIDEO(VIDEO_TITULO,VIDEO_CATEGORIA,VIDEO_DATA,VIDEO_HORA,FK_USUARIO)
VALUES  ("O AMANHECER","COMEDIA","01/02/2024","01:45",1),
	("O ANOITECER","COMEDIA","01/02/2024","01:45",2),
	("O ANO NOVO","COMEDIA","01/02/2024","01:45",3);
	
SELECT * FROM VIDEO;

	
CREATE TABLE COMENTARIO(
	COMENTARIO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	COMENTARIO_CORPO VARCHAR(500) NOT NULL,
	COMENTARIO_DATA DATE NOT NULL,
	COMENTARIO_HORA TIME NOT NULL,
	FK_USUARIO INT(10) NOT NULL,
	CONSTRAINT FK_COMENTARIO_USUARIO_ID FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(USUARIO_ID));
	
CREATE TABLE CLASSIFICACAO(
	CLASSIFICACAO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	CLASSIFICACAO_DESCRICAO VARCHAR(255) NOT NULL,
	FK_USUARIO INT(10) NOT NULL,
	FK_VIDEO INT(10) NOT NULL);

ALTER TABLE CLASSIFICACAO ADD CONSTRAINT CLASSIFICACAO_FK_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE;
ALTER TABLE CLASSIFICACAO ADD CONSTRAINT CLASSIFICACAO_FK_VIDEO FOREIGN KEY (FK_VIDEO) REFERENCES VIDEO(VIDEO_ID) ON DELETE CASCADE;

ALTER TABLE CLASSIFICACAO DROP CONSTRAINT CLASSIFICAO_FK_USUARIO;

CREATE TABLE CATEGORIA(
	CATEGORIA_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	CATEGORIA_NOME VARCHAR(255) NOT NULL UNIQUE);
	
CREATE TABLE CATEGORIA_VIDEO(
	FK_CATEGORIA INT(10) NOT NULL,
	FK_VIDEO INT(10) NOT NULL);
	
ALTER TABLE CATEGORIA_VIDEO ADD CONSTRAINT CATEGORIA_VIDEO_FK_CATEGORIA FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA(CATEGORIA_ID);
ALTER TABLE CATEGORIA_VIDEO ADD CONSTRAINT CATEGORIA_VIDEO_FK_VIDEO FOREIGN KEY (FK_VIDEO) REFERENCES VIDEO(VIDEO_ID);



