// <auto-generated />
using System;
using LojaGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaGames.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421204200_update1")]
    partial class update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.Models.Console", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descritivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("Game.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdConsole")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Game.Models.Game_Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdGame")
                        .HasColumnType("int");

                    b.Property<int>("IdLoja")
                        .HasColumnType("int");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LojaId");

                    b.ToTable("Games_Lojas");
                });

            modelBuilder.Entity("Game.Models.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("Game.Models.Game", b =>
                {
                    b.HasOne("Game.Models.Console", "Console")
                        .WithMany("Games")
                        .HasForeignKey("ConsoleId");

                    b.Navigation("Console");
                });

            modelBuilder.Entity("Game.Models.Game_Loja", b =>
                {
                    b.HasOne("Game.Models.Game", "Game")
                        .WithMany("Games_Lojas")
                        .HasForeignKey("GameId");

                    b.HasOne("Game.Models.Loja", "Loja")
                        .WithMany("Games_Lojas")
                        .HasForeignKey("LojaId");

                    b.Navigation("Game");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Game.Models.Console", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Game.Models.Game", b =>
                {
                    b.Navigation("Games_Lojas");
                });

            modelBuilder.Entity("Game.Models.Loja", b =>
                {
                    b.Navigation("Games_Lojas");
                });
#pragma warning restore 612, 618
        }
    }
}
