// <auto-generated />
using System;
using LojaGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaGames.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaGames.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameConsoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdConsole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameConsoleId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LojaGames.Models.GameConsole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descritivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameConsoles");
                });

            modelBuilder.Entity("LojaGames.Models.Game_Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdLoja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LojaId");

                    b.ToTable("Games_Lojas");
                });

            modelBuilder.Entity("LojaGames.Models.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("LojaGames.Models.Game", b =>
                {
                    b.HasOne("LojaGames.Models.GameConsole", "GameConsole")
                        .WithMany("Games")
                        .HasForeignKey("GameConsoleId");

                    b.Navigation("GameConsole");
                });

            modelBuilder.Entity("LojaGames.Models.Game_Loja", b =>
                {
                    b.HasOne("LojaGames.Models.Game", "Game")
                        .WithMany("Games_Lojas")
                        .HasForeignKey("GameId");

                    b.HasOne("LojaGames.Models.Loja", "Loja")
                        .WithMany("Games_Lojas")
                        .HasForeignKey("LojaId");

                    b.Navigation("Game");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaGames.Models.Game", b =>
                {
                    b.Navigation("Games_Lojas");
                });

            modelBuilder.Entity("LojaGames.Models.GameConsole", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("LojaGames.Models.Loja", b =>
                {
                    b.Navigation("Games_Lojas");
                });
#pragma warning restore 612, 618
        }
    }
}
